version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: app/logs/cfts_log.log
    maxBytes:  10485760 # 10MB
    backupCount: 50     # Retain max 50 log files
    mode: 'w'  
loggers:
  consoleLogger:
    level: INFO
    handlers: [console,file]
    propagate: no
root:
  level: INFO
  handlers: [console,file]